Properly retain types of Mapping subclasses
samuelcolvin/pydantic pull request #2325
Opened 2021-02-07 16:39 UTC by ofek

## Change Summary

This change prevents Mapping subclasses from always being coerced to `dict`

## Related issue number

Resolves #2323 

## Checklist

* [X] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [X] Documentation reflects the changes where applicable
* [X] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

2021-02-07 21:38 UTC, ofek commented
@PrettyWood I'm not sure how to fix the type checking errors

2021-02-07 23:01 UTC, ofek commented
@PrettyWood The current job failure is due to https://pypi.org/project/cryptography/3.4.1/ emitting a warning in the test suite of FastAPI

2021-02-07 23:08 UTC, PrettyWood commented
Yep can't do anything about that now but it should be handled rapidly on FastAPI side.
In the meantime you can add some tests to keep coverage at 100% :)

2021-02-08 04:22 UTC, ofek commented
Done!

2021-02-08 08:35 UTC, PrettyWood requested changes
@ofek We should still check the set type and try to coerce when needed.
For example
```py
class M(BaseModel):
    x: Dict[str, int]
```
should coerce to `dict`. Right now there is no difference between `Dict` and `Mapping`...
I updated https://github.com/PrettyWood/pydantic/pull/70/files if you want

-----------------------------------------------------------------

Note that I think we should probably have a proper validator for `Dict` (at least) before `Mapping` to avoid any performance impact on normal dictionaries (like it's done for `Tuple` or `List`, which are treated before `Sequence`)

2021-02-08 15:07 UTC, ofek commented
Updated based on your branch

2021-02-09 17:52 UTC, PrettyWood reviewed
I still reckon we should at least have `SHAPE_DICT` (extra could be `SHAPE_DEFAULTDICT`, `SHAPE_COUNTER`...) before `SHAPE_MAPPING` to have no perf impact.
Or at least if we go with it we should have a benchmark to see the impact

2021-02-09 17:52 UTC, PrettyWood commented on pydantic/fields.py
> +        if target_type is dict:
```suggestion
        if target_type in {dict, Dict}:
```

2021-02-09 17:52 UTC, PrettyWood commented on pydantic/fields.py
> +        if target_type is dict:
For python 3.6, `__origin__` is `typing.Dict`, which is just an alias for `dict`

2021-02-09 17:52 UTC, PrettyWood commented on pydantic/fields.py
> +        elif target_type is defaultdict:
```suggestion
        elif target_type in {defaultdict, DefaultDict}:
```
same

2021-02-09 17:52 UTC, PrettyWood commented on pydantic/fields.py
> +            return defaultdict(getattr(original, 'default_factory', None), **converted)
```suggestion
            return defaultdict(getattr(original, 'default_factory', None), converted)
```
and same under.
If we use `kwargs`, it won't work for `int` keys. But it does when passing a dict as `arg`.
Same under

2021-02-10 16:32 UTC, ofek commented
@PrettyWood Addressed. I'm not familiar with the concept of shapes here. Can you explain?

2021-02-10 16:46 UTC, PrettyWood commented
@ofek _pydantic_ is fast because a lot is done in the metaclass. You can have a look at `ModelField._type_analysis()`, which is run in `ModelMetaclass` when `ModelField.infer()` is called.
In `_type_analysis` a lot is done to set the right attributes to each ModelField (type, shape, validators...)
And the `shape` is used to call the right default validators to speed up the parsing

2021-02-10 17:19 UTC, ofek commented
I just tried that but many tests are failing now

2021-02-10 18:27 UTC, ofek commented
should I revert the last commit for now?

2021-02-11 16:21 UTC, ofek commented
I'm still trying but I don't understand what's wrong 🙁

2021-02-12 17:28 UTC, ofek commented
@PrettyWood Could you please take a look when you get a chance?

2021-02-12 17:30 UTC, PrettyWood commented
I'll have a look tonight or tomorrow 👍

2021-02-12 17:34 UTC, ofek commented
Thank you, feel free to push directly to my branch!

2021-02-13 09:52 UTC, PrettyWood commented
Hi @ofek
Had a quick look and got all tests working in local https://github.com/PrettyWood/pydantic/pull/70
I have some guests coming around soon but I think you should be able to work it out without a problem
I think you still need to add some tests to showcase a random mapping getting coerced into `dict` when `Dict[...]` is set.
Hope it helps

2021-02-13 15:00 UTC, ofek commented
@PrettyWood Done! Added that test too

2021-02-14 12:19 UTC, samuelcolvin reviewed
otherwise this is looking good.

2021-02-14 12:19 UTC, samuelcolvin commented on tests/test_main.py
> +        field: Mapping[str, Mapping[str, int]]
this is a very confusing name for a field.

2021-02-14 12:19 UTC, samuelcolvin commented on tests/test_main.py
> +    class Map(dict):
```suggestion
    class CustomMap(dict):
```
might be a clearer name?

2021-02-14 12:46 UTC, ofek commented
@samuelcolvin Thanks, addressed!

2021-02-16 05:23 UTC, ofek commented
Done this look alright now?

2021-02-17 21:28 UTC, ofek commented
@samuelcolvin Just let me know if I have to do anything else! FYI, after this is merged and released, every [Datadog Agent integration](https://github.com/DataDog/integrations-core) will exclusively use pydantic for user configuration 🙂

2021-02-25 17:27 UTC, merged

2021-02-25 17:28 UTC, samuelcolvin commented
This is great. Thank you.

> @samuelcolvin Just let me know if I have to do anything else! FYI, after this is merged and released, every [Datadog Agent integration](https://github.com/DataDog/integrations-core) will exclusively use pydantic for user configuration 🙂

I don't see pydantic as a dependency, what am I missing?

2021-02-25 17:38 UTC, PrettyWood commented
@samuelcolvin https://github.com/DataDog/integrations-core/pull/8675

2021-03-22 17:41 UTC, ofek commented
https://github.com/DataDog/integrations-core/pull/8675 is merged and I've started the syncing of every integration: https://github.com/DataDog/integrations-core/pulls 😄

2021-03-29 19:52 UTC, ofek commented
https://datadoghq.dev/integrations-core/meta/config-models/