Add lookahead for ip check in AnyUrl
samuelcolvin/pydantic pull request #2512
Opened 2021-03-11 20:30 UTC by sbv-csis

## Change Summary

Added lookahead for the ip regex'es to allow for urls with 4 numbers preceeding the rest of the host

## Related issue number
#1651 

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

2021-03-13 14:30 UTC, PrettyWood requested changes
Thanks a lot for having a look at this! 🙏 
Unfortunately there is a test case that used to pass and now fails. I suggest you add it
```py
def test_ipv4_no_port():
    url = validate_url('ftp://123.45.67.8')
    assert url.scheme == 'ftp'
    assert url.host == '123.45.67.8'
    assert url.host_type == 'ipv4'
    assert url.port is None
    assert url.user is None
    assert url.password is None
```

2021-03-13 14:30 UTC, PrettyWood commented on changes/2512-sbv-csis.md
> +Add lookahead to ip regexes for AnyUrl hosts. This allows urls with DNS labels
```suggestion
Add lookahead to ip regexes for `AnyUrl` hosts. This allows urls with DNS labels 
```

2021-03-15 09:05 UTC, sbv-csis commented
> Thanks a lot for having a look at this! 
> Unfortunately there is a test case that used to pass and now fails. I suggest you add it
> 
> ```python
> def test_ipv4_no_port():
>     url = validate_url('ftp://123.45.67.8')
>     assert url.scheme == 'ftp'
>     assert url.host == '123.45.67.8'
>     assert url.host_type == 'ipv4'
>     assert url.port is None
>     assert url.user is None
>     assert url.password is None
> ```

Thanks for the feedback and good catch!
I've added the test and updated the regex - I've made it to match the one used to end the `domain` group (minus the \s, I don't think that makes sense)

2021-03-15 10:00 UTC, PrettyWood approved these changes
LGTM!

2021-03-24 09:27 UTC, sbv-csis commented
Should/could I do anything else here with this or are we on track for the next steps?

2021-04-27 07:27 UTC, GitHK commented
Will this PR be merged, if yes is there a way to understand when it will be released?
Thanks.

2021-05-09 09:49 UTC, merged

2021-05-09 09:50 UTC, samuelcolvin commented
this is great, thank you so much.

@GitHK I'm aiming to make a new release over the coming weeks, but as you can see there are a lot of PRs to review. If you're hoping for a new release soon, perhaps you could speed things up by reviewing any on PRs with the "ready for review" badge?