Fix issue with generic type aliases forward refs resolving
samuelcolvin/pydantic pull request #2802
Opened 2021-05-16 16:28 UTC by uriyyo

## Change Summary

Fix issue with generic type aliases forward refs resolving

## Related issue number

#2798

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2021-05-16 19:51 UTC, uriyyo commented
please review

2021-06-07 18:22 UTC, FeeeeK commented
Will this pull request be accepted?
It also fixes a bug with type aliases like this:
```python
ListOfModels = typing.List["Model"]

class Model(BaseModel):
    pass

class Example(BaseModel):
    a = ListOfModels
```

2021-06-09 07:27 UTC, uriyyo commented
Hi @FeeeeK,

Could you please provide more context?

From what I see, there are no problems with code that you provide.
Code below should be executed without errors:
```py
import typing

from pydantic import BaseModel

ListOfModels = typing.List["Model"]


class Model(BaseModel):
    pass


class Example(BaseModel):
    a: ListOfModels


print(Example(a=[Model()]))
```

I will try to add more context on what case this PR will fix.

Basically when you pass str as a typing generic parameter it will be automatically wrapped with `ForwardRef`:
```py
>>> List["Foo"]
typing.List[ForwardRef('Foo')]
```

But in case of a builtin generic aliases it will not be wrapped:
```py
>>> list["Foo"]
list['Foo']
```

2021-06-10 14:54 UTC, FeeeeK commented
In my case, I had to call `Example.update_forward_refs()` twice.

Otherwise there would be an error:
`field "response" not yet prepared so type is still a ForwardRef, you might need to call SendUserIdsResponse.update_forward_refs().`
[Model](https://github.com/timoniq/vkbottle-types/blob/d635892e09e2efbd9eeb0c7c7c05cba4f26b5064/vkbottle_types/responses/messages.py#L172)
[Alias](https://github.com/timoniq/vkbottle-types/blob/d635892e09e2efbd9eeb0c7c7c05cba4f26b5064/vkbottle_types/responses/messages.py#L370)

2021-09-04 22:12 UTC, PrettyWood requested changes
Please update

2021-09-04 22:12 UTC, PrettyWood commented on tests/test_generics.py
> +only_39 = pytest.mark.skipif(
`above_39` maybe since in fact it's also 3.10 now ;)

2021-09-04 22:12 UTC, PrettyWood commented on pydantic/typing.py
> +    def normalize_type(tp: Type[Any]) -> Type[Any]:
Can you add a docstring with a input -> output example pls?

2021-09-04 22:12 UTC, PrettyWood commented on pydantic/fields.py
>          self.outer_type_: Any = type_
What about outer_type?

2021-09-04 22:12 UTC, PrettyWood commented on changes/2803-uriyyo.md
> +Fix issue when `update_forward_refs` fail to resolve `ForwardRef`
I think it's easier to have one change file with the PR number with both points inside (key for mappings + normalize)

2022-04-02 16:23 UTC, uriyyo commented
#3681 has better implementation and will fix the same issues as this PR

2022-04-02 16:23 UTC, closed without merging