Fix missing enum extra
samuelcolvin/pydantic pull request #2818
Opened 2021-05-20 05:07 UTC by sammchardy

## Change Summary

Models with an enum and Field definiton that just has **extra params now includes these in the output

```   
   class Names(str, Enum):
        rick = 'Rick'
        morty = 'Morty'
        summer = 'Summer'

    class Foo(BaseModel):
        enum: Names
        extra_enum: Names = Field(..., extra='Extra field')
```

Before
```
{
        'definitions': {
            'Names': {
                'description': 'An enumeration.',
                'enum': ['Rick', 'Morty', 'Summer'],
                'title': 'Names',
                'type': 'string',
            },
        },
        'properties': {
            'enum': {'$ref': '#/definitions/Names'},
            'extra_enum': {'$ref': '#/definitions/Names'},
        },
        'required': ['enum', 'extra_enum'],
        'title': 'Foo',
        'type': 'object',
}
```

After
```
{
        'definitions': {
            'Names': {
                'description': 'An enumeration.',
                'enum': ['Rick', 'Morty', 'Summer'],
                'title': 'Names',
                'type': 'string',
            },
        },
        'properties': {
            'enum': {'$ref': '#/definitions/Names'},
            'extra_enum': {'allOf': [{'$ref': '#/definitions/Names'}], 'extra': 'Extra field'},
        },
        'required': ['enum', 'extra_enum'],
        'title': 'Foo',
        'type': 'object',
}
```

## Related issue number

This resolves https://github.com/samuelcolvin/pydantic/issues/2697

## Checklist

* [y] Unit tests for the changes exist
* [y] Tests pass on CI and coverage remains at 100%
* [n/a ] Documentation reflects the changes where applicable
* [y] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [y] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2021-05-23 23:13 UTC, sammchardy commented
please review

2021-09-04 21:19 UTC, PrettyWood requested changes
Other than that LGTM! 👍

2021-09-04 21:19 UTC, PrettyWood commented on changes/2697-sammchardy.md
> +from being saved to the json schema output
```suggestion
`Enum` fields now properly support extra kwargs in schema generation
```
Or something like that...
No need to be specific in the implementation, more what's the solved issue ;)

2021-09-04 21:19 UTC, PrettyWood commented
please update

2021-09-23 07:27 UTC, sammchardy commented
@PrettyWood updated

2021-12-07 14:10 UTC, PrettyWood approved these changes
Thanks!

2021-12-07 14:10 UTC, merged