clarify docs on validation and strict type checking
samuelcolvin/pydantic pull request #2855
Opened 2021-05-28 21:33 UTC by paxcodes

## Change Summary

Clarify docs about Pydantic's support for custom validation and strict type checking, despite that pydantic is primarily a parsing library.

## Related issue number

Issue#578

## Checklist

* [n/a] Unit tests for the changes exist
* [n/a] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2021-05-28 22:10 UTC, paxcodes commented
Please review @PrettyWood

2021-06-04 21:45 UTC, PrettyWood requested changes

2021-06-04 21:45 UTC, PrettyWood commented on changes/2855-paxcodes.md
> +Clarify documentation about `pydantic`'s support for custom validation and strict type checking, despite `pydantic` being primarily a parsing library.
```suggestion
Clarify documentation about _pydantic_'s support for custom validation and strict type checking, despite _pydantic_ being primarily a parsing library.
```

2021-06-04 21:45 UTC, PrettyWood commented on docs/usage/models.md
> +Nevertheless, [strict type checking](types.md#strict-types) is supported.
I would have said partially supported. We'll need to wait for https://github.com/samuelcolvin/pydantic/issues/1098 to have a full (and easy to use) strict type checking

2021-06-04 21:45 UTC, PrettyWood commented
Please update and rebase/merge with master. Thanks!

2021-07-15 14:03 UTC, paxcodes commented
Please review.

2021-09-04 17:58 UTC, PrettyWood approved these changes
Great!

2021-09-04 17:58 UTC, merged