Add annotation to ModelField for use in BaseModel.__signature__
samuelcolvin/pydantic pull request #3413
Opened 2021-11-14 03:55 UTC by adriangb

Currently, `ModelField.outer_type_` is used for `Model.__signature__`.

This leads to signatures that differ from dataclasses or classes with a manual `__init__` of the same types.

```python
from dataclasses import dataclass
from inspect import signature
from typing import Optional

from pydantic import BaseModel

@dataclass
class Dataclass:
    foo: Optional[int] = None

class CustomClass:
    def __init__(self, foo: Optional[int] = None) -> None:
        ...

class PydanticModel(BaseModel):
    foo: Optional[int] = None

print(signature(Dataclass).parameters["foo"].annotation)  # Optional[int]
print(signature(CustomClass).parameters["foo"].annotation)  # Optional[int]
print(signature(PydanticModel).parameters["foo"].annotation)  # <class 'int'>
```

This PR fixes this by storing the annotation in `ModelField.annotation` and then using that for the signature instead of `outer_type_`.
I realize this is adding a public attribute to `ModelField`, and that it is not as simple as storing the `type_` passed into the constructor (I tried to handle the case where the type is inferred from the default value, I think successfully), so this may not be the best solution, but it is the best I could come up with today.

2022-04-02 12:55 UTC, samuelcolvin requested changes
Seems good to me, but please add a change description.

I don't think this can go in v1.9.1 as it's not a bug fix for v1.9

2022-04-02 12:55 UTC, samuelcolvin commented
please update.

2022-04-02 13:26 UTC, adriangb commented
Hmm. While I am adding a public attribute, and that could be considered a feature, I am only doing it to fix what I would consider a bug (incorrect results from `inspect.signsture`). One of my main questions here was: can you think of a way of doing this that does not add a public attribute?

2022-04-02 17:29 UTC, samuelcolvin commented
I don't mind the public attribute, I don't see another (simply) way.

Which of my points were you questioning? The current description, out which release this goes in?

2022-04-02 17:39 UTC, adriangb commented
I was just questioning if this is a bug fix or a feature. I think the underlying problem is a bug, but if we're adding a public attribute it's more like a feature.

I'll add the change description.

2022-04-02 18:19 UTC, samuelcolvin reviewed
Otherwise lgtm

2022-04-02 18:19 UTC, samuelcolvin commented on changes/3413-fix-inspect-signature.md
> +fix mangling of inspect.signature for BaseModel
```suggestion
fix mangling of `inspect.signature` for `BaseModel`
```

2022-05-06 02:15 UTC, adriangb commented
@samuelcolvin I guess we didn't merge this 😅

2022-08-05 13:49 UTC, samuelcolvin commented
> @samuelcolvin I guess we didn't merge this sweat_smile

Got there in the end :sweat:.

Thank so much, as ever, _sorry for the delay_.

2022-08-05 14:11 UTC, JacobHayes commented
@samuelcolvin looks like this one won't auto-merge because of the [old "request changes"](https://github.com/samuelcolvin/pydantic/pull/3413#pullrequestreview-929568495) - I think it'll need an approval to override.

2022-08-05 14:13 UTC, samuelcolvin approved these changes

2022-08-05 14:13 UTC, merged

2022-08-05 14:14 UTC, samuelcolvin commented
Thanks @JacobHayes, missed that.

2022-08-05 14:18 UTC, JacobHayes commented
Yup, I missed the auto-merge announcement so excited to find it in the wild!

2022-08-05 14:18 UTC, samuelcolvin commented
Ye, it's been a god sent for this work.