Add docs for defining upper-case variables on nested Settings models
samuelcolvin/pydantic pull request #4153
Opened 2022-06-11 16:05 UTC by aminalaee

## Change Summary

The reason explained here: https://github.com/samuelcolvin/pydantic/issues/3936#issuecomment-1152903692

## Related issue number

Add docs for #3936

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2022-06-11 16:05 UTC, aminalaee commented
please review

2022-07-05 17:58 UTC, hramezani approved these changes

2022-07-05 18:00 UTC, hramezani commented on docs/usage/settings.md
> +set `case_sensitive=True` to disable this behaviour.
```suggestion
set `case_sensitive=True` to disable this behavior.
```

2022-07-05 18:00 UTC, hramezani requested changes
Thanks @aminalaee for the PR :+1: 
Please update your PR and fix the small typo.

2022-07-05 18:01 UTC, hramezani commented
please update

2022-07-05 18:04 UTC, hramezani approved these changes

2022-07-05 18:04 UTC, merged

2022-07-05 18:11 UTC, aminalaee commented
Thanks @hramezani 🚀